### ISSUE TITLE
Nova prijava

### ISSUE THREAD

**Issue by strojanski** [strojanski/terrsko#2]
Prijavi se z boljšim opisom projekta

**Comment by gabrijelokorn** [comment]
![Terrsko](https://user-images.githubusercontent.com/79152818/221382828-5e12ff04-d6a3-41f2-9b90-d0b5a154b9b9.png)

**Comment by strojanski** [comment]
A si tut ze oddal novo prijavo?

**Comment by gabrijelokorn** [comment]
Aja ne sm mislu da boš to ti.
